[tikv]
enabled = true
migrate_target = true
# If you have many pd address, use ',' split then:
#   pdaddrs = "pdhost1:2379, pdhost2:2379, pdhost3:2379"
   
pdaddrs = "192.168.2.71:2379"
    
# Concurrency for TiKV delete range
deleterange_concurrency = 1

# Enable 1PC 
enable_1pc = true
 
[rocksdb]
enabled = true
dir = "/data/filer_rocksdb"