// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: private/v1/tapeio.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteToTapeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files    []*WriteToTapeFileInfo `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Pools    []string               `protobuf:"bytes,2,rep,name=pools,proto3" json:"pools,omitempty"`
	Replicas int32                  `protobuf:"varint,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
}

func (x *WriteToTapeRequest) Reset() {
	*x = WriteToTapeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_v1_tapeio_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteToTapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteToTapeRequest) ProtoMessage() {}

func (x *WriteToTapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_private_v1_tapeio_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteToTapeRequest.ProtoReflect.Descriptor instead.
func (*WriteToTapeRequest) Descriptor() ([]byte, []int) {
	return file_private_v1_tapeio_proto_rawDescGZIP(), []int{0}
}

func (x *WriteToTapeRequest) GetFiles() []*WriteToTapeFileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *WriteToTapeRequest) GetPools() []string {
	if x != nil {
		return x.Pools
	}
	return nil
}

func (x *WriteToTapeRequest) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

type WriteToTapeFileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReadFrom *DataLocation `protobuf:"bytes,2,opt,name=read_from,json=readFrom,proto3" json:"read_from,omitempty"`
}

func (x *WriteToTapeFileInfo) Reset() {
	*x = WriteToTapeFileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_v1_tapeio_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteToTapeFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteToTapeFileInfo) ProtoMessage() {}

func (x *WriteToTapeFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_private_v1_tapeio_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteToTapeFileInfo.ProtoReflect.Descriptor instead.
func (*WriteToTapeFileInfo) Descriptor() ([]byte, []int) {
	return file_private_v1_tapeio_proto_rawDescGZIP(), []int{1}
}

func (x *WriteToTapeFileInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WriteToTapeFileInfo) GetReadFrom() *DataLocation {
	if x != nil {
		return x.ReadFrom
	}
	return nil
}

type WriteToTapeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*WriteToTapeResult `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *WriteToTapeResponse) Reset() {
	*x = WriteToTapeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_v1_tapeio_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteToTapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteToTapeResponse) ProtoMessage() {}

func (x *WriteToTapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_private_v1_tapeio_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteToTapeResponse.ProtoReflect.Descriptor instead.
func (*WriteToTapeResponse) Descriptor() ([]byte, []int) {
	return file_private_v1_tapeio_proto_rawDescGZIP(), []int{2}
}

func (x *WriteToTapeResponse) GetData() []*WriteToTapeResult {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteToTapeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error   string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Tapes   []string `protobuf:"bytes,4,rep,name=tapes,proto3" json:"tapes,omitempty"`
}

func (x *WriteToTapeResult) Reset() {
	*x = WriteToTapeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_v1_tapeio_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteToTapeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteToTapeResult) ProtoMessage() {}

func (x *WriteToTapeResult) ProtoReflect() protoreflect.Message {
	mi := &file_private_v1_tapeio_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteToTapeResult.ProtoReflect.Descriptor instead.
func (*WriteToTapeResult) Descriptor() ([]byte, []int) {
	return file_private_v1_tapeio_proto_rawDescGZIP(), []int{3}
}

func (x *WriteToTapeResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WriteToTapeResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteToTapeResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WriteToTapeResult) GetTapes() []string {
	if x != nil {
		return x.Tapes
	}
	return nil
}

type ReadFromTapeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []*ReadFromTapeFileInfo `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *ReadFromTapeRequest) Reset() {
	*x = ReadFromTapeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_v1_tapeio_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFromTapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFromTapeRequest) ProtoMessage() {}

func (x *ReadFromTapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_private_v1_tapeio_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFromTapeRequest.ProtoReflect.Descriptor instead.
func (*ReadFromTapeRequest) Descriptor() ([]byte, []int) {
	return file_private_v1_tapeio_proto_rawDescGZIP(), []int{4}
}

func (x *ReadFromTapeRequest) GetFiles() []*ReadFromTapeFileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type ReadFromTapeFileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WriteTo *DataLocation `protobuf:"bytes,2,opt,name=write_to,json=writeTo,proto3" json:"write_to,omitempty"`
}

func (x *ReadFromTapeFileInfo) Reset() {
	*x = ReadFromTapeFileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_v1_tapeio_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFromTapeFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFromTapeFileInfo) ProtoMessage() {}

func (x *ReadFromTapeFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_private_v1_tapeio_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFromTapeFileInfo.ProtoReflect.Descriptor instead.
func (*ReadFromTapeFileInfo) Descriptor() ([]byte, []int) {
	return file_private_v1_tapeio_proto_rawDescGZIP(), []int{5}
}

func (x *ReadFromTapeFileInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReadFromTapeFileInfo) GetWriteTo() *DataLocation {
	if x != nil {
		return x.WriteTo
	}
	return nil
}

type ReadFromTapeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ReadFromTapeResult) Reset() {
	*x = ReadFromTapeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_v1_tapeio_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFromTapeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFromTapeResult) ProtoMessage() {}

func (x *ReadFromTapeResult) ProtoReflect() protoreflect.Message {
	mi := &file_private_v1_tapeio_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFromTapeResult.ProtoReflect.Descriptor instead.
func (*ReadFromTapeResult) Descriptor() ([]byte, []int) {
	return file_private_v1_tapeio_proto_rawDescGZIP(), []int{6}
}

func (x *ReadFromTapeResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReadFromTapeResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadFromTapeResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReadFromTapeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*ReadFromTapeResult `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ReadFromTapeResponse) Reset() {
	*x = ReadFromTapeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_private_v1_tapeio_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFromTapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFromTapeResponse) ProtoMessage() {}

func (x *ReadFromTapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_private_v1_tapeio_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFromTapeResponse.ProtoReflect.Descriptor instead.
func (*ReadFromTapeResponse) Descriptor() ([]byte, []int) {
	return file_private_v1_tapeio_proto_rawDescGZIP(), []int{7}
}

func (x *ReadFromTapeResponse) GetData() []*ReadFromTapeResult {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_private_v1_tapeio_proto protoreflect.FileDescriptor

var file_private_v1_tapeio_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x61, 0x70,
	0x65, 0x69, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x15, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x12,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x54, 0x6f, 0x54, 0x61, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x35, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x54, 0x6f, 0x54, 0x61, 0x70, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x6f,
	0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6f, 0x6f, 0x6c, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x22, 0x5c, 0x0a, 0x13, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x54, 0x6f, 0x54, 0x61, 0x70, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x35, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x08, 0x72, 0x65, 0x61, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x22, 0x48, 0x0a, 0x13, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x54, 0x6f, 0x54, 0x61, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x54, 0x6f, 0x54, 0x61, 0x70, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x69, 0x0a, 0x11, 0x57, 0x72, 0x69, 0x74, 0x65, 0x54, 0x6f, 0x54, 0x61,
	0x70, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x70, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x70, 0x65, 0x73, 0x22, 0x4d,
	0x0a, 0x13, 0x52, 0x65, 0x61, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x61, 0x70, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x61, 0x70, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x5b, 0x0a,
	0x14, 0x52, 0x65, 0x61, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x61, 0x70, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x33, 0x0a, 0x08, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x74,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x07, 0x77, 0x72, 0x69, 0x74, 0x65, 0x54, 0x6f, 0x22, 0x54, 0x0a, 0x12, 0x52, 0x65,
	0x61, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x61, 0x70, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x4a, 0x0a, 0x14, 0x52, 0x65, 0x61, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x61, 0x70, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x61, 0x70, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xaf, 0x01, 0x0a,
	0x06, 0x54, 0x61, 0x70, 0x65, 0x49, 0x4f, 0x12, 0x50, 0x0a, 0x0b, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x54, 0x6f, 0x54, 0x61, 0x70, 0x65, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x54, 0x6f, 0x54, 0x61, 0x70, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x54, 0x6f, 0x54, 0x61, 0x70, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0c, 0x52, 0x65, 0x61,
	0x64, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x61, 0x70, 0x65, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x54,
	0x61, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x46, 0x72, 0x6f, 0x6d,
	0x54, 0x61, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2e,
	0x5a, 0x2c, 0x67, 0x69, 0x74, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x68, 0x79, 0x2d,
	0x64, 0x61, 0x74, 0x61, 0x2f, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x2d, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_private_v1_tapeio_proto_rawDescOnce sync.Once
	file_private_v1_tapeio_proto_rawDescData = file_private_v1_tapeio_proto_rawDesc
)

func file_private_v1_tapeio_proto_rawDescGZIP() []byte {
	file_private_v1_tapeio_proto_rawDescOnce.Do(func() {
		file_private_v1_tapeio_proto_rawDescData = protoimpl.X.CompressGZIP(file_private_v1_tapeio_proto_rawDescData)
	})
	return file_private_v1_tapeio_proto_rawDescData
}

var file_private_v1_tapeio_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_private_v1_tapeio_proto_goTypes = []any{
	(*WriteToTapeRequest)(nil),   // 0: private.v1.WriteToTapeRequest
	(*WriteToTapeFileInfo)(nil),  // 1: private.v1.WriteToTapeFileInfo
	(*WriteToTapeResponse)(nil),  // 2: private.v1.WriteToTapeResponse
	(*WriteToTapeResult)(nil),    // 3: private.v1.WriteToTapeResult
	(*ReadFromTapeRequest)(nil),  // 4: private.v1.ReadFromTapeRequest
	(*ReadFromTapeFileInfo)(nil), // 5: private.v1.ReadFromTapeFileInfo
	(*ReadFromTapeResult)(nil),   // 6: private.v1.ReadFromTapeResult
	(*ReadFromTapeResponse)(nil), // 7: private.v1.ReadFromTapeResponse
	(*DataLocation)(nil),         // 8: private.v1.DataLocation
}
var file_private_v1_tapeio_proto_depIdxs = []int32{
	1, // 0: private.v1.WriteToTapeRequest.files:type_name -> private.v1.WriteToTapeFileInfo
	8, // 1: private.v1.WriteToTapeFileInfo.read_from:type_name -> private.v1.DataLocation
	3, // 2: private.v1.WriteToTapeResponse.data:type_name -> private.v1.WriteToTapeResult
	5, // 3: private.v1.ReadFromTapeRequest.files:type_name -> private.v1.ReadFromTapeFileInfo
	8, // 4: private.v1.ReadFromTapeFileInfo.write_to:type_name -> private.v1.DataLocation
	6, // 5: private.v1.ReadFromTapeResponse.data:type_name -> private.v1.ReadFromTapeResult
	0, // 6: private.v1.TapeIO.WriteToTape:input_type -> private.v1.WriteToTapeRequest
	4, // 7: private.v1.TapeIO.ReadFromTape:input_type -> private.v1.ReadFromTapeRequest
	2, // 8: private.v1.TapeIO.WriteToTape:output_type -> private.v1.WriteToTapeResponse
	7, // 9: private.v1.TapeIO.ReadFromTape:output_type -> private.v1.ReadFromTapeResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_private_v1_tapeio_proto_init() }
func file_private_v1_tapeio_proto_init() {
	if File_private_v1_tapeio_proto != nil {
		return
	}
	file_private_v1_meta_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_private_v1_tapeio_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*WriteToTapeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_private_v1_tapeio_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*WriteToTapeFileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_private_v1_tapeio_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*WriteToTapeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_private_v1_tapeio_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*WriteToTapeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_private_v1_tapeio_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ReadFromTapeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_private_v1_tapeio_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ReadFromTapeFileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_private_v1_tapeio_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ReadFromTapeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_private_v1_tapeio_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ReadFromTapeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_private_v1_tapeio_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_private_v1_tapeio_proto_goTypes,
		DependencyIndexes: file_private_v1_tapeio_proto_depIdxs,
		MessageInfos:      file_private_v1_tapeio_proto_msgTypes,
	}.Build()
	File_private_v1_tapeio_proto = out.File
	file_private_v1_tapeio_proto_rawDesc = nil
	file_private_v1_tapeio_proto_goTypes = nil
	file_private_v1_tapeio_proto_depIdxs = nil
}
