name: Build And Push

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "Select the type of build to execute"
        type: choice
        required: true
        default: "udm"
        options:
          - udm
          - udm_rocksdb
          - filer_migrate_tool
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Alicloud Docker registry
      uses: docker/login-action@v2
      with:
        registry: vdm-registry.cn-hangzhou.cr.aliyuncs.com
        username: ${{ secrets.ALI_REGISTRY_USER }}
        password: ${{ secrets.ALI_REGISTRY_PASS }}
    - name: Build and push Docker images
      run: |
        GOPROXY=https://proxy.golang.org,direct make ${{ github.event.inputs.build_type }}
